- defaults:
    link:
      relink: true
      create: true
      force: true
      type: symlink
    shell:
      quiet: true

- clean: ["~", "~/.local/bin"]

- link:
    # Binaries
    ~/.local/bin:
      glob: true
      path: windows/bin/*

    # Shell
    ~/Documents/PowerShell:
      glob: true
      path: windows/shell/powershell/*

    ~/.vimrc: shell/vimrc.vim

    ~/.config/git: config/git
    ~\AppData\Roaming\bottom: config/bottom
    ~\AppData\Roaming\bat: config/bat
    ~\AppData\Roaming\eza: config/eza
    ~\AppData\Config\btop: config/btop

- create:
    - ~/Downloads
    - ~/Dev
    - ~/Tmp

- shell:
    - [bat cache --build, Reloading bat configs]
