- defaults:
    link:
      relink: true
      create: true
      force: true
      type: symlink
    create:
      mode: 0700
    shell:
      quiet: true

- clean:
    ~/:
    ~/.local/bin:
    ~/.config:
      recursive: true

- link:
    # Binaries
    ~/.local/bin:
      glob: true
      path: bin/*

    # Shell
    ~/.local/bin/env: shell/env.sh
    ~/.bashrc: shell/bash/bashrc.sh

    ~/.zshrc: shell/zsh/zshrc.zsh
    ~/.zshenv: shell/zsh/zshenv.zsh
    ~/.oh-my-zsh/custom:
      glob: true
      path: shell/zsh/autoload/*

    # Config dir
    ~/.config:
      glob: true
      path: config/*

    # Termux
    ~/.termux:
      if: '[ -n "$TERMUX_VERSION" ]'
      glob: true
      path: termux/termux/*

- create:
    - ~/dev
    - ~/tmp
