- defaults:
    link:
      relink: true
      create: true
      force: true
      type: symlink
    create:
      mode: 0700
    shell:
      quiet: true

- clean:
    ~/:
    ~/.local/bin:
    ~/.config:
      recursive: true

- link:
    # Binaries
    ~/.local/bin:
      glob: true
      path: bin/*

    # Shell
    ~/.bashrc: shell/bash/bashrc.sh

    ~/.zshrc: shell/zsh/zshrc.zsh
    ~/.zshenv: shell/zsh/zshenv.zsh
    ~/.oh-my-zsh/custom/utils.zsh:
      if: "[ -d ~/.oh-my-zsh ]"
      path: shell/zsh/utils.zsh
    ~/.oh-my-zsh/custom/aliases.zsh:
      if: "[ -d ~/.oh-my-zsh ]"
      path: shell/zsh/aliases.zsh

    ~/.tmux.conf: shell/tmux.conf.tmux
    ~/.vimrc: shell/vimrc.vim

    # Config dir
    ~/.config:
      glob: true
      path: config/*
      exclude: [config/Code]

    # Vs Code
    ~/.config/Code:
      glob: true
      path: config/Code/*
    ~/.config/VSCodium:
      glob: true
      path: config/Code/*

    # Termux
    ~/.termux:
      if: '[ -n "$TERMUX_VERSION" ]'
      glob: true
      path: termux/termux/*
      exclude: [termux/termux/boot, termux/termux/widget]

- create:
    - ~/downloads
    - ~/dev
    - ~/tmp

- shell:
    - [bat cache --build, Reloading bat configs]
