- defaults:
    link:
      relink: true
      create: true
      force: true
      type: symlink
    create:
      mode: 0700
    shell:
      quiet: true

- clean:
    [
      "~",
      "~/.config",
      "~/.local/bin",
      "~/.oh-my-zsh/custom",
      "~/.local/share/oh-my-zsh/custom",
    ]

- link:
    # Binaries
    ~/.local/bin:
      glob: true
      path: bin/*

    # Config dir
    ~/.config:
      glob: true
      path: config/*

    # Shell
    ~/.local/bin/env: shell/env.sh
    ~/.bashrc: shell/bash/bashrc.sh

    ~/.zshrc: shell/zsh/zshrc.zsh
    ~/.zshenv: shell/zsh/zshenv.zsh
    ~/.local/share/oh-my-zsh/custom:
      if: '[ -d "$HOME/.local/share/oh-my-zsh" ]'
      glob: true
      path: shell/zsh/autoload/*
    ~/.oh-my-zsh/custom:
      if: '[ -d "$HOME/.oh-my-zsh" ]'
      glob: true
      path: shell/zsh/autoload/*

    # Termux
    ~/.termux:
      if: '[ -n "$TERMUX_VERSION" ]'
      glob: true
      path: termux/termux/*

- create:
    - ~/dev
    - ~/tmp
