excludes = []

[formatter.dprint]
command = "dprint"
options = ["fmt"]
includes = ["*.json", "*.jsonc", "*.yaml", "*.yml", "*.md"]

[formatter.tombi]
command = "tombi"
options = ["format"]
includes = ["*.toml"]

[formatter.shfmt]
command = "shfmt"
options = ["-w", "-i", "2", "-ci", "-bn", "-sr"]
includes = ["*.sh", "*.bash"]

[formatter.fish_indent]
command = "fish_indent"
options = ["-w"]
includes = ["*.fish", "**/fish_variables"]

[formatter.nufmt]
command = "nufmt"
includes = ["*.nu"]

[formatter.just]
command = "just"
options = ["--fmt", "-f"]
includes = ["justfile", "**/justfile", "*.just"]

[formatter.stylua]
command = "stylua"
includes = ["*.lua"]
