- defaults:
    link:
      relink: true
      create: true
      force: true
      type: symlink
    create:
      mode: 0755

- clean: ["~", "~/.config", "~/.local/bin", "${ZSH_CUSTOM}", "~/.termux"]

- link:
    # Binaries
    ~/.local/bin/:
      glob: true
      path: bin/*

    # Config dir
    ~/.config/:
      glob: true
      path: config/*

    # Shell
    ~/.local/bin/env: shell/env.sh
    ~/.bashrc: shell/bash/bashrc.bash

    ~/.zshrc:
      if: "command -v zsh"
      path: shell/zsh/zshrc.zsh
    ~/.zshenv:
      if: "command -v zsh"
      path: shell/zsh/zshenv.zsh
    ${ZSH_CUSTOM}/:
      if: '[ -n "$ZSH_CUSTOM" ] && [ -d "$ZSH_CUSTOM" ]'
      path: shell/zsh/autoload/*
      glob: true

    # Termux
    ~/.termux/:
      if: '[ -n "$TERMUX_VERSION" ]'
      path: termux/*
      glob: true

- create:
    - ~/dev
    - ~/tmp
