- defaults:
    link:
      relink: true
      create: true
      force: true
      type: symlink
    create:
      mode: 0755

- clean: ["~", "~/.config", "~/.local/bin", "~/.termux"]

- link:
    # Binaries
    ~/.local/bin/:
      glob: true
      path: bin/*

    # Config dir
    ~/.config/:
      glob: true
      path: config/*

    # Bash
    ~/.bashrc:
      if: "command -v bash"
      path: bashrc.bash

    # Termux
    ~/.termux/:
      if: '[ -n "$TERMUX_VERSION" ]'
      path: termux/*
      glob: true

- create:
    - ~/dev
    - ~/tmp
