- defaults:
    link:
      relink: true
      create: true
      force: true
      type: symlink

- clean: ["~", "~/.config", "~/.local/bin", "~/.termux"]

- link:
    # Editorconfig
    ~/.editorconfig: editorconfig.ini

    # Config dir
    ~/.config/:
      glob: true
      path: config/*
      exclude: [ config/mise-cli ]
    ~/.config/mise: config/mise-cli

    # Bash
    ~/.bashrc:
      if: "command -v bash"
      path: bashrc.bash

    # Termux
    ~/.termux/:
      if: '[ -n "$TERMUX_VERSION" ]'
      path: termux/*
      glob: true
