- defaults:
    link:
      relink: true
      create: true
      force: true
      type: symlink

- clean:
    ["~", "~/.config", "~/.local/bin", "~/AppData/Local", "~/AppData/Roaming"]

- link:
    # Editorconfig
    ~/.editorconfig: .editorconfig

    # Configs
    ~/.config/git: config/git
    ~/.config/mise: config/mise-cli
    ~/AppData/Roaming/bat: config/bat
    ~/AppData/Roaming/nushell: config/nushell
    ~/AppData/Roaming/yazi/config: config/yazi
    ~/AppData/Local/nvim: config/nvim

- create:
    - ~/Dev
    - ~/Tmp
