" NOTE: This is a self-contained configuration for bare vim/neovim.

" ========== Appearance ==========

set background=dark
set laststatus=2

set notermguicolors
set t_Co=16

colorscheme habamax

" Cursor style
let &t_SI = "\<Esc>[5 q"
let &t_EI = "\<Esc>[2 q"
let &t_SR = "\<Esc>[4 q"


" ========== Main settings ==========

set encoding=utf-8
set fileencodings=utf-8

set modelines=0 " Disable CVE-2007-2438 vulnerability

set updatetime=300

syntax on

set ruler " Show current cursor position
set mouse=a " Enable mouse

set clipboard=unnamedplus

" Line numbers
set relativenumber
set number
set numberwidth=3

set scrolloff=5
set signcolumn=yes
set cursorline

" Autocomplete in command-mode
set wildmode=longest,list,full
set wildmenu

" Tabulation
set expandtab
set tabstop=4
set shiftwidth=4
set softtabstop=4
set smarttab

set backspace=indent,eol,start " More capability for delete text
filetype plugin indent on

" Disable backups
set nobackup
set nowritebackup
set noswapfile
set noundofile
set viminfofile=NONE

" Search
set incsearch " Search as you type
set ignorecase " Ignore register
set smartcase " Ignore register if no capital letters


" ========== Functions ==========

" Toggle background transparency
let t:isTransparent = 1
function! ToggleBGTransparency()
    if t:isTransparent
        hi Normal guibg=NONE ctermbg=NONE
        hi NonText guibg=NONE ctermbg=NONE
        hi SignColumn ctermbg=NONE guibg=NONE
        let t:isTransparent = 0
    else
        colorscheme habamax
        let t:isTransparent = 1
    endif
endfunction

" Toggle word wrap
let t:isWordWrap = 1
function! ToggleWordWrap()
    if t:isWordWrap
        set nowrap
        let t:isWordWrap = 0
    else
        set wrap
        let t:isWordWrap = 1
    endif
endfunction


" ========== Autocommands ==========
au VimEnter * call ToggleBGTransparency() " Transparent background
au VimEnter * call ToggleWordWrap() " Disable wrap
au CmdlineEnter /,? set hlsearch " Enable hlsearch at enter to search


" ========== Keys ==========

" Change leaders
let mapleader = " "
let maplocalleader = "\\"

nnoremap <Esc> :set nohlsearch<CR>

nnoremap <leader>sb :call ToggleBGTransparency()<CR>
nnoremap <leader>sw :call ToggleWordWrap()<CR>
nnoremap <leader>ss :setlocal spell!<CR>

nnoremap <leader>w :wa<CR>

