return {
  { "mason-org/mason.nvim", enabled = false },
  { "mason-org/mason-lspconfig.nvim", enabled = false },
  {
    "nvim-treesitter/nvim-treesitter",
    opts = {
      ensure_installed = {
        "just",
        "editorconfig",
        "ini",
        "kdl",
        "typst",
        "fish",
        "nu",
        "go",
        "rust",
        "zig",
        "cpp",
      },
    },
  },
  {
    "stevearc/conform.nvim",
    opts = {
      formatters_by_ft = {
        kdl = { "kdlfmt" },
        nu = { "nufmt" },
        tmux = { "shfmt" },
        markdown = { "dprint" },
        ["markdown.mdx"] = { "dprint" },
        yaml = { "dprint" },
        dockerfile = { "dprint" },
        xml = { "dprint" },
        json = { "biome" },
        jsonc = { "biome" },
        html = { "biome" },
        css = { "biome" },
        graphql = { "biome" },
        javascript = { "biome" },
        typescript = { "biome" },
        javascriptreact = { "biome" },
        typescriptreact = { "biome" },
      },
    },
  },
  {
    "neovim/nvim-lspconfig",
    opts = {
      servers = {
        typos_lsp = {},
        just = {},
        tombi = {},
        tinymist = {
          single_file_support = true,
          settings = {
            formatterMode = "typstyle",
          },
        },
        nushell = {},
        rust_analyzer = {},
        zls = {},
        clangd = {},
        gopls = {},
        biome = {},
        ruff = {},
        ty = {},
      },
    },
  },
}
