### Languages

[settings]
npm.package_manager = "bun"
pipx.uvx = true
python.uv_venv_auto = true

[tools]

# Rust
rust = { version = "latest", components = ["rust-analyzer", "rust-src"] }

# Lua
lua = "latest"
stylua = "latest"
"aqua:Kampfkarren/selene" = "latest"
lua-language-server = "latest"

# Go
go = "latest"
"go:golang.org/x/tools/gopls" = "latest"

# Zig/C/C++
zig = "latest"
"github:zigtools/zls" = "latest"
"github:clangd/clangd" = "latest"
"npm:clang-format" = "latest"

# Python
uv = "latest"
python = { version = "latest", venv_backend = "uv" }
ruff = "latest"
ty = "latest"

# JS/TS
bun = "latest"
biome = "latest"

# Typst
typst = "latest"
typstyle = "latest"
tinymist = "latest"

shfmt = "latest"                    # Shell
taplo = "latest"                    # Toml
"github:hougesen/kdlfmt" = "latest" # Kdl

# Just
just = "latest"
"github:terror/just-lsp" = "latest"

# Spell
typos = "latest"
"github:tekumara/typos-lsp" = "latest"
