# NOTE: Independent tmux config

### Enable features

# True Color
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

# For images
set -g allow-passthrough on
set -ga update-environment TERM
set -ga update-environment TERM_PROGRAM

### Main settings

set -g prefix C-a
set -g mouse on
set -g focus-events on
set -g status-position top
set -s escape-time 0
set -g history-limit 10000

# First index
set -g base-index 1
setw -g pane-base-index 1

## Change keybindings

bind s choose-tree -sZ -O name # Sort by name

unbind %
bind | split-window -h

unbind '"'
bind - split-window -v

unbind r
bind r run-shell 'tmux source-file "#{config_files}"' \; display "Config reloaded" # Reload settings

# Resize pane
bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5
bind -r h resize-pane -L 5
bind -r m resize-pane -Z

## Like Vim
setw -g mode-keys vi

# Visual mode and copy
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection
unbind -T copy-mode-vi MouseDragEnd1Pane
